language: java

cache:
  directories:
    - $HOME/.m2

sudo: false

services:
  - docker

install: true

script:
  - "./mvnw -version"
  - "./mvnw -Pjava11 clean dependency:list test -Pall-dbs${NO_JACOCO:+',no-jacoco'} -Dsort -U"
